version: '2.1'
services:
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/data:/prometheus-data
        ports:
            - 9090:9090
    grafana:
        image: grafana/grafana
        volumes:
            - ./grafana:/var/lib/grafana
        ports:
            - 3000:3000
